name: syntax-optics
version: 0.1.0.1
license: BSD3
author: "Yair Chuchem"
maintainer: "yairchu@gmail.com"
copyright: 2020 Yair Chuchem"

extra-source-files:
- README.md

dependencies:
- base >= 4.9 && <5
- constraints
- lens >= 5
- semigroupoids
- tagged

default-extensions:
- DeriveFunctor
- FlexibleContexts
- FlexibleInstances
- LambdaCase
- MultiParamTypeClasses
- ScopedTypeVariables
- TupleSections
- TypeApplications

library:
  source-dirs: src
  ghc-options:
  - -fexpose-all-unfoldings
  - -Wall
  - -Wnoncanonical-monad-instances
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

tests:
  syntax-optics-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - syntax-optics
